/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'tertiary-fixed-dim': '#bdcabe',
        'on-surface': '#191c1b',
        'secondary-fixed-dim': '#90d792',
        'surface-variant': '#e1e3e1',
        'surface-container-highest': '#e1e3e1',
        background: '#f8faf8',
        'tertiary-fixed': '#d9e6da',
        'surface-tint': '#1b6d24',
        'secondary-fixed': '#abf4ac',
        'on-tertiary-container': '#e8f5e9',
        primary: '#0d631b',
        'on-error-container': '#93000a',
        error: '#ba1a1a',
        'on-secondary': '#ffffff',
        tertiary: '#4d5950',
        surface: '#f8faf8',
        'on-tertiary-fixed-variant': '#3e4a41',
        'surface-container-lowest': '#ffffff',
        'primary-fixed-dim': '#88d982',
        'surface-container': '#eceeec',
        'on-primary-fixed-variant': '#005312',
        'inverse-primary': '#88d982',
        'on-primary': '#ffffff',
        'surface-container-low': '#f2f4f2',
        'on-secondary-container': '#2e7238',
        'surface-dim': '#d8dad9',
        'secondary-container': '#abf4ac',
        'surface-bright': '#f8faf8',
        'on-secondary-fixed-variant': '#07521d',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-primary-fixed': '#002204',
        'on-tertiary': '#ffffff',
        'inverse-surface': '#2e3130',
        'inverse-on-surface': '#eff1ef',
        'primary-fixed': '#a3f69c',
        'on-primary-container': '#cbffc2',
        'on-surface-variant': '#40493d',
        'tertiary-container': '#657167',
        'outline-variant': '#bfcaba',
        'on-background': '#191c1b',
        secondary: '#286b33',
        'primary-container': '#2e7d32',
        'surface-container-high': '#e6e9e7',
        'on-tertiary-fixed': '#131e17',
        'on-secondary-fixed': '#002107',
        outline: '#707a6c',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        sm: '12px',
        lg: '40px',
        'container-margin': '20px',
        base: '8px',
        xl: '64px',
        md: '24px',
        xs: '4px',
        gutter: '16px',
      },
      fontFamily: {
        'headline-md': ['Inter'],
        'label-sm': ['Inter'],
        'body-lg': ['Inter'],
        'headline-lg-mobile': ['Inter'],
        'body-md': ['Inter'],
        display: ['Inter'],
        'headline-lg': ['Inter'],
        'label-md': ['Inter'],
      },
      fontSize: {
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.03em', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'headline-lg-mobile': ['28px', { lineHeight: '34px', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        display: ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
};
